language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
#  - "2.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy libnetcdf netcdf4 pytest
  - pip install -r test-requirements.txt
  - pip install codecov pytest-cov
  - python setup.py install

script:
  - py.test --cov --cov-report=term-missing -vv

after_success:
  - codecov
