language: python

sudo: false

python:
  - "2.7"
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip atlas numpy=1.11.2 scipy=0.18.1 libnetcdf netcdf4=1.2.4 pytest=3.0.5
  - pip install -r requirements_dev.txt
  - pip install codecov pytest-cov
  - python setup.py install

before_script:
  # Download the required climatology files.
  - python -c "import oceansdb; oceansdb.WOA()['TEMP']"
  - python -c "import oceansdb; oceansdb.CARS()['TEMP']"
  - python -c "import oceansdb; oceansdb.ETOPO()"

script:
  - py.test --cov --cov-report=term-missing -vv

after_success:
  - codecov
