# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "3.4"
  - "3.3"
  - "2.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy libnetcdf netcdf4 pytest
#  - pip install -U pip
  - pip install -r test-requirements.txt
  - python setup.py install

# Run test
script: py.test tests
